PROGRAM = main

# One of "ram" or "flash"
MODE = flash

# One of "hd" or "md" or "cl"
DENSITY = hd

# Object files
OBJS = main.o flash_if.o stm32f10x_flash.o

include ../Makefile.inc

INCCFLAGS += -I../common
VPATH    += ../common


